// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfaetjvodhrdzivzdmxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmYWV0anZvZGhyZHppdnpkbXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjUwNDksImV4cCI6MjA2Mzg0MTA0OX0.MnHdzF8oKt69nMl3Ys2gOIl91TMNgwc6ESTC2H_Os1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);